-- Membership checks are inlined in RLS policies (EXISTS on workspace_members).
-- No SECURITY DEFINER helper: avoids authenticated EXECUTE advisor WARN.
-- workspace_members SELECT is own-row only so inlined EXISTS does not recurse.
